using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DojoTracker.Models
{
    public class DojoList
    {
        private static Dojo[] _dojos = {
                
                new Dojo { Id = 1, Title = "String Calculator", Description = "", Difficulty = 1, Url = "https://osherove.com/tdd-kata-1" },
                new Dojo { Id = 2, Title = "Bank OCR", Description = "", Difficulty = 2, Url = "http://codingdojo.org/kata/BankOCR/" },
                new Dojo { Id = 3, Title = "SOLID: S", Description = "", Difficulty = 1, Url = "https://github.com/CodecoolGlobal/solid-kata" },
                new Dojo { Id = 4, Title = "SOLID: O", Description = "", Difficulty = 1, Url = "https://github.com/CodecoolGlobal/solid-kata" },
                new Dojo { Id = 5, Title = "SOLID: L", Description = "", Difficulty = 1, Url = "https://github.com/CodecoolGlobal/solid-kata" },
                new Dojo { Id = 6, Title = "SOLID: I", Description = "", Difficulty = 1, Url = "https://github.com/CodecoolGlobal/solid-kata" },
                new Dojo { Id = 7, Title = "SOLID: D", Description = "", Difficulty = 1, Url = "https://github.com/CodecoolGlobal/solid-kata" },
                new Dojo { Id = 8, Title = "Pattern: State", Description = "", Difficulty = 1, Url = "https://www.codewars.com/kata/5682e72eb7354b2f39000021" },
                new Dojo { Id = 9, Title = "Pattern: Strategy", Description = "", Difficulty = 1, Url = "https://www.codewars.com/kata/patterncraft-strategy" },
                new Dojo { Id = 10, Title = "Pattern: Visitor", Description = "", Difficulty = 1, Url = "https://www.codewars.com/kata/patterncraft-visitor" },
                new Dojo { Id = 11, Title = "Pattern: Decorator", Description = "", Difficulty = 1, Url = "https://www.codewars.com/kata/patterncraft-decorator" },
                new Dojo { Id = 12, Title = "Pattern: Adapter", Description = "", Difficulty = 2, Url = "https://www.codewars.com/kata/patterncraft-adapter" },
                new Dojo { Id = 13, Title = "Pattern: Command", Description = "", Difficulty = 2, Url = "https://www.codewars.com/kata/patterncraft-command" },
                new Dojo { Id = 14, Title = "Pattern: Observer", Description = "", Difficulty = 2, Url = "https://www.tutorialspoint.com/design_pattern/observer_pattern.htm" },
                new Dojo { Id = 15, Title = "Pattern: Proxy", Description = "", Difficulty = 2, Url = "https://www.tutorialspoint.com/design_pattern/proxy_pattern.htm" },
                new Dojo { Id = 16, Title = "Pattern: Chain of Responsibility", Description = "", Difficulty = 3, Url = "https://www.tutorialspoint.com/design_pattern/chain_of_responsibility_pattern.htm" },
                new Dojo { Id = 17, Title = "Warmup: Sock Merchant", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/sock-merchant/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=warmup" },
                new Dojo { Id = 18, Title = "Warmup: Counting Valleys", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/counting-valleys/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=warmup" },
                new Dojo { Id = 19, Title = "Warmup: Jumping on theClouds", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/jumping-on-the-clouds/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=warmup" },
                new Dojo { Id = 20, Title = "Warmup: Repeated String", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/repeated-string/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=warmup" },
                new Dojo { Id = 21, Title = "Arrays: Left Rotation", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/ctci-array-left-rotation/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=arrays" },
                new Dojo { Id = 22, Title = "Arrays: New Year Chaos", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/new-year-chaos/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=arrays" },
                new Dojo { Id = 23, Title = "Arrays: Minimum Swaps 2", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/minimum-swaps-2/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=arrays" },
                new Dojo { Id = 24, Title = "Dictionaries: Two Strings", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/two-strings/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=dictionaries-hashmaps" },
                new Dojo { Id = 25, Title = "Dictionaries: Sherlock and Anagrams", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/sherlock-and-anagrams/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=dictionaries-hashmaps" },
                new Dojo { Id = 26, Title = "Dictionaries: Count Triplets", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/count-triplets-1/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=dictionaries-hashmaps" },
                new Dojo { Id = 27, Title = "Dictionaries: Frequency Queries", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/frequency-queries/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=dictionaries-hashmaps" },
                new Dojo { Id = 28, Title = "Sorting: Bubble Sort", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/ctci-bubble-sort/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=sorting" },
                new Dojo { Id = 29, Title = "Sorting: Comparator", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/ctci-comparator-sorting/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=sorting" },
                new Dojo { Id = 30, Title = "Sorting: Fraudulent Activity Notifications", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/fraudulent-activity-notifications/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=sorting" },
                new Dojo { Id = 31, Title = "Sorting: Making Anagrams", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/ctci-making-anagrams/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=strings" },
                new Dojo { Id = 32, Title = "String: Sherlock and the Valid String", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/sherlock-and-valid-string/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=strings" },
                new Dojo { Id = 33, Title = "String: Special String Again", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/special-palindrome-again/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=strings" },
                new Dojo { Id = 34, Title = "String: Common Child", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/common-child/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=strings" },
                new Dojo { Id = 35, Title = "Greedy Algorithms: Minimum Absolute Difference in an Array", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/minimum-absolute-difference-in-an-array/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=greedy-algorithms" },
                new Dojo { Id = 36, Title = "Greedy Algorithms: Greedy Florist", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/greedy-florist/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=greedy-algorithms" },
                new Dojo { Id = 37, Title = "Greedy Algorithms: Max Min", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/angry-children/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=greedy-algorithms" },
                new Dojo { Id = 38, Title = "Search: Ice Cream Parlor", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/ctci-ice-cream-parlor/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=search" },
                new Dojo { Id = 39, Title = "Search: Swap Nodes", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/swap-nodes-algo/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=search" },
                new Dojo { Id = 40, Title = "Search: Pairs", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/pairs/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=search" },
                new Dojo { Id = 41, Title = "Search: Triple Sum", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/triple-sum/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=search" },
                new Dojo { Id = 42, Title = "Search: Minimum Time Required", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/minimum-time-required/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=search" },
                new Dojo { Id = 43, Title = "Dynamic Programming: Abbreviation", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/abbr/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=dynamic-programming" },
                new Dojo { Id = 44, Title = "Dynamic Programming: Max Array Sum", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/max-array-sum/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=dynamic-programming" },
                new Dojo { Id = 45, Title = "Dynamic Programming: Candies", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/candies/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=dynamic-programming" },
                new Dojo { Id = 46, Title = "Stacks and Queues: Balanced Brackets", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/balanced-brackets/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=stacks-queues" },
                new Dojo { Id = 47, Title = "Stacks and Queues: A Tale of Two Stacks", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/ctci-queue-using-two-stacks/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=stacks-queues" },
                new Dojo { Id = 48, Title = "Stacks and Queues: Largest Rectangle", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/largest-rectangle/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=stacks-queues" },
                new Dojo { Id = 49, Title = "Stacks and Queues: Min Max Riddle", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/min-max-riddle/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=stacks-queues" },
                new Dojo { Id = 50, Title = "Stacks and Queues: Castle on the Grid", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/castle-on-the-grid/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=stacks-queues" },
                new Dojo { Id = 51, Title = "Graphs: Roads and Libraries", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/torque-and-development/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=graphs" },
                new Dojo { Id = 52, Title = "Graphs: Find the Nearest Clone", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/find-the-nearest-clone/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=graphs" },
                new Dojo { Id = 53, Title = "Trees: Height of Binary Tree", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/tree-height-of-a-binary-tree/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=trees" },
                new Dojo { Id = 54, Title = "Trees: Lowest Common Ancestor", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/binary-search-tree-lowest-common-ancestor/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=trees" },
                new Dojo { Id = 55, Title = "Trees: Is This A Binary Search Tree?", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/ctci-is-binary-search-tree/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=trees" },
                new Dojo { Id = 56, Title = "Trees: Huffman Decoding", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/tree-huffman-decoding/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=trees" },
                new Dojo { Id = 57, Title = "Linked List: Insert a Node at a Specific Position", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/insert-a-node-at-a-specific-position-in-a-linked-list/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=linked-lists" },
                new Dojo { Id = 58, Title = "Linked List: Inserting a Node Into a Sorted Doubly Linked List", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/insert-a-node-into-a-sorted-doubly-linked-list/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=linked-lists" },
                new Dojo { Id = 59, Title = "Linked List: Reverse a Doubly Linked List", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/reverse-a-doubly-linked-list/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=linked-lists" },
                new Dojo { Id = 60, Title = "Linked List: Find Merge Point of Two Lists", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/find-the-merge-point-of-two-joined-linked-lists/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=linked-lists" },
                new Dojo { Id = 61, Title = "Linked List: Detect a Cycle", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/ctci-linked-list-cycle/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=linked-lists" },
                new Dojo { Id = 62, Title = "Recursion: Fibonacci Numbers", Description = "", Difficulty = 1, Url = "https://www.hackerrank.com/challenges/ctci-fibonacci-numbers/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=recursion-backtracking" },
                new Dojo { Id = 63, Title = "Recursion: Davis' Staircase", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/ctci-recursive-staircase/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=recursion-backtracking" },
                new Dojo { Id = 64, Title = "Recursion: Crossword Puzzle", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/crossword-puzzle/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=recursion-backtracking" },
                new Dojo { Id = 65, Title = "Recursion: Digit Sum", Description = "", Difficulty = 2, Url = "https://www.hackerrank.com/challenges/recursive-digit-sum/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=recursion-backtracking" },
                new Dojo { Id = 66, Title = "FizzBuzz", Description = "", Difficulty = 1, Url = "http://codingdojo.org/kata/FizzBuzz" }
        };

        public static Dojo[] Dojos { get { return _dojos; }}
    }
}
